const fs = require("fs")
const path = require("path")
const { withDangerousMod } = require("@expo/config-plugins")

function withSentryXcodeEnv(config) {
  return withDangerousMod(config, [
    "ios",
    async (modConfig) => {
      const iosDir = modConfig.modRequest.platformProjectRoot
      const xcodeEnvPath = path.join(iosDir, ".xcode.env")

      if (!fs.existsSync(xcodeEnvPath)) {
        return modConfig
      }

      let content = fs.readFileSync(xcodeEnvPath, "utf8")

      const blockStart = "# >>> SENTRY_EXPO_AUTO >>>"
      const blockEnd = "# <<< SENTRY_EXPO_AUTO <<<"
      const blockRegex = new RegExp(
        `${blockStart}[\\s\\S]*?${blockEnd}\\n?`,
        "g"
      )

      content = content.replace(blockRegex, "").trimEnd()

      const sentryBlock = [
        blockStart,
        "# Auto-generated by Expo config plugin.",
        "# Reads SENTRY_AUTH_TOKEN from project root .env files for Xcode Archive.",
        "if [[ -f \"$PROJECT_ROOT/.env\" ]]; then",
        "  export $(grep -E '^[A-Za-z_][A-Za-z0-9_]*=' \"$PROJECT_ROOT/.env\" | xargs) >/dev/null 2>&1 || true",
        "fi",
        "if [[ -f \"$PROJECT_ROOT/.env.local\" ]]; then",
        "  export $(grep -E '^[A-Za-z_][A-Za-z0-9_]*=' \"$PROJECT_ROOT/.env.local\" | xargs) >/dev/null 2>&1 || true",
        "fi",
        "if [[ -f \"$PROJECT_ROOT/.env.production\" ]]; then",
        "  export $(grep -E '^[A-Za-z_][A-Za-z0-9_]*=' \"$PROJECT_ROOT/.env.production\" | xargs) >/dev/null 2>&1 || true",
        "fi",
        blockEnd,
      ].join("\n")

      const nextContent = `${content}\n\n${sentryBlock}\n`
      fs.writeFileSync(xcodeEnvPath, nextContent)

      return modConfig
    },
  ])
}

module.exports = withSentryXcodeEnv
