import { StyleSheet } from 'react-native';
import { Colors } from '../../constants/Colors';

/** Canonical geometry from the approved onboarding weekly plan. */
export const planningStyles = StyleSheet.create({
  mealDay: { fontFamily: 'CronosProBold', fontSize: 13, color: '#C24C0B', marginBottom: 4 },
  nutritionNote: { marginTop: 8, fontFamily: 'CronosPro', fontSize: 14, lineHeight: 19, color: Colors.light.textSecondary },
  days: { gap: 7, paddingVertical: 17 }, day: { width: 51, height: 61, borderRadius: 17, backgroundColor: 'white', borderWidth: 1, borderColor: '#EFE8CF', alignItems: 'center', justifyContent: 'center' }, dayActive: { backgroundColor: Colors.light.button, borderColor: Colors.light.button }, dayShort: { fontFamily: 'CronosProBold', fontSize: 11, color: Colors.light.textSecondary, textTransform: 'capitalize' }, dayNumber: { fontFamily: 'Degular', fontSize: 19, color: Colors.light.text, marginTop: 1 }, dayTextActive: { color: 'white' },
  summary: { padding: 16, borderRadius: 23, backgroundColor: 'white', borderWidth: 1, borderColor: '#EFE8CF' }, summaryTop: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' }, summaryEyebrow: { fontFamily: 'CronosPro', fontSize: 12, color: Colors.light.textSecondary }, summaryCalories: { marginTop: 2, fontFamily: 'Degular', fontSize: 27, color: Colors.light.text }, summaryUnit: { fontFamily: 'CronosPro', fontSize: 13, color: Colors.light.textSecondary }, goalCheck: { width: 31, height: 31, borderRadius: 16, backgroundColor: Colors.light.button, alignItems: 'center', justifyContent: 'center' }, calorieTrack: { height: 7, marginTop: 11, borderRadius: 4, overflow: 'hidden', backgroundColor: '#F1EBD8' }, calorieFill: { height: '100%', borderRadius: 4, backgroundColor: Colors.light.button }, macros: { flexDirection: 'row', gap: 12, marginTop: 14 }, macro: { flex: 1, flexDirection: 'row', alignItems: 'center', gap: 7 }, macroDot: { width: 7, height: 28, borderRadius: 4 }, macroValue: { fontFamily: 'CronosProBold', fontSize: 14, color: Colors.light.text }, macroLabel: { fontFamily: 'CronosPro', fontSize: 10, color: Colors.light.textSecondary },
  sectionRow: { flexDirection: 'row', alignItems: 'baseline', marginTop: 20, marginBottom: 10 }, sectionTitle: { fontFamily: 'Degular', fontSize: 23, color: Colors.light.text }, meals: { gap: 12 }, mealCard: { overflow: 'hidden', borderRadius: 23, backgroundColor: 'white', shadowColor: '#000', shadowOffset: { width: 0, height: 4 }, shadowOpacity: 0.05, shadowRadius: 12, elevation: 3 }, mealMain: { minHeight: 116, flexDirection: 'row', alignItems: 'center', gap: 12, padding: 10 }, imageWrap: { width: 103, height: 96, borderRadius: 18, overflow: 'hidden', backgroundColor: '#F1EACB' }, mealImage: { width: '100%', height: '100%' }, imageLoading: { ...StyleSheet.absoluteFill, alignItems: 'center', justifyContent: 'center', backgroundColor: 'rgba(30,32,29,0.25)' }, mealTypePill: { position: 'absolute', left: 7, bottom: 7, paddingHorizontal: 8, paddingVertical: 4, borderRadius: 10, backgroundColor: 'rgba(255,255,255,0.92)' }, mealType: { fontFamily: 'CronosProBold', fontSize: 10, color: Colors.light.button, textTransform: 'uppercase' }, mealBody: { flex: 1, minWidth: 0 }, mealTitle: { fontFamily: 'Degular', fontSize: 19, lineHeight: 21, color: Colors.light.text }, mealMetaRow: { flexDirection: 'row', alignItems: 'center', flexWrap: 'wrap', marginTop: 7, gap: 5 }, mealMeta: { fontFamily: 'CronosPro', fontSize: 12, color: Colors.light.textSecondary }, mealMetaStrong: { fontFamily: 'CronosProBold', fontSize: 12, color: '#D95A4C' }, metaDot: { width: 3, height: 3, borderRadius: 2, backgroundColor: '#C4BCA6' }, timeRow: { flexDirection: 'row', alignItems: 'center', gap: 4, marginTop: 6 }, timeText: { fontFamily: 'CronosPro', fontSize: 12, color: Colors.light.textSecondary }, swapRow: { minHeight: 37, borderTopWidth: 1, borderTopColor: '#F2ECD9', flexDirection: 'row', gap: 6, alignItems: 'center', justifyContent: 'center' }, swapText: { fontFamily: 'CronosProBold', fontSize: 12, color: Colors.light.button },
  valueRow: { flexDirection: 'row', gap: 11, alignItems: 'center', backgroundColor: '#EFF7F1', borderRadius: 20, padding: 14, marginTop: 15 }, valueIcon: { width: 42, height: 42, borderRadius: 15, backgroundColor: '#DDF0E2', alignItems: 'center', justifyContent: 'center' }, valueCopy: { flex: 1 }, valueTitle: { fontFamily: 'Degular', fontSize: 17, color: '#315E41' }, valueText: { marginTop: 1, fontFamily: 'CronosPro', fontSize: 12, lineHeight: 16, color: '#52705C' }, disclaimer: { marginTop: 12, color: Colors.light.textSecondary, fontFamily: 'CronosPro', fontSize: 11, lineHeight: 15, textAlign: 'center' },
});
